config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :rooms do
  resources :reservations
  end

  root to: 'pages#home'


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    
    validates :start_date, :end_date, :overlap => {:scope => "room_id"}

    belongs_to :room


end

app/models/room.rb
class Room < ApplicationRecord

    has_many :reservations, dependent: :destroy

    has_one_attached :thumbnail_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, :only => [:show , :index]
  before_action :set_reservation, only: %i[ show edit update destroy ]
  before_action :get_room



  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
    @reservations = @room.reservations
  end

  # GET /reservations/new
  def new
    @reservation = @room.reservations.build

  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = @room.reservations.build(reservation_params)

    respond_to do |format|
      if @reservation.save
        ReservationConfirmationMailer.with(reservation: @reservation).reservation_confirmation_email.deliver_now

        format.html { redirect_to root_path, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to room_reservations_path(@room), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to room_reservations_path(@room), notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
     def get_room
      @room = Room.find(params[:room_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = @room.reservations.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:name, :last_name, :email, :persons, :start_date, :end_date, :message, :room_id)
    end
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :description, :thumbnail_image, :images, :person)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookingapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
 

<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
  </head>

  <body>
   

 
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/navbar" %>

<section id="hero" class="d-flex align-items-center">
    <div class="container" data-aos="zoom-out" data-aos-delay="100">
      <h1>Make a <br>reservation</h1>
      <h2>Toplik Rooms su smještajni kapaciteti smješteni uz sami restoran i urađeni u prirodnom stilu, od 100% prirodnih materijala. Naše sobe su namijenjene putnicima namjernicima koji žele odmor u miru i tišini, van gradske guzve. Sobe posjeduju sve potrebne elemente za kvalitetan odmor. Noćenja su sa uključenim doručkom. Polupansione takođe radimo u dogovoru sa našim gostima. Ugodan boravak u našem Topliku!</h2>
      <div class="d-flex">
        <%= link_to  rooms_path , class: "btn-get-started scrollto" do %>
        Book Now
     <%= image_tag "arrow.svg" %>
        <% end %>
      </div>
    </div>
  </section>

app/views/reservations/_form.html.erb
<%= form_with(model: [ @room ,reservation], local: true) do |form| %>
<%= form.hidden_field :room_id, :value => @room.id%>

<% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


 <div class="container-fluid">
       <div class="row">
           <div class="col-12 col-md-8 bg-light">
             <div class="container mt-5 mx-5">
               <p class="font-poppins-48"> Confirm <br> your reservation</p>
             </div>
             <div class="container col-md-10 bg-white mt-2 pt-4 px-5">
               <div class="row align-items-stretch no-gutters contact-wrap">
                 <div class="col-md-12">
                   <div class="form h-100">
                     <form class="mb-5" method="post" id="contactForm" name="contactForm">
                       <div class="row">
                         <div class="col-md-4 form-group mt-4 mb-4">
                           <label for="" class="col-form-label">Name</label>
                               <%= form.text_field :name, class: "form-control" %>

                         </div>
                         <div class="col-md-4 form-group mt-4 mb-4">
                           <label for="" class="col-form-label">Last Name</label>
                             <%= form.text_field :last_name, class: "form-control" %>
                         </div>
                         <div class="col-md-4 form-group mt-4 mb-4">
                           <label for="" class="col-form-label">Email address</label>
                                <%= form.text_field :email, class: "form-control" %>
                         </div>
                       </div>

                       <div class="row">
                         <div class="col-md-4 form-group mt-4 mb-4">
                           <label for="" class="col-form-label">Number of persons</label>
                            <%= form.text_field :persons, class: "form-control" %>
                            
                         </div>
                         <div class="col-md-4 form-group mt-4 mb-4">
                           <label for="" class="col-form-label">Arrival date</label>
                               <%= form.date_field :start_date, class: "form-control" %>

                         </div>
                         <div class="col-md-4 form-group mt-4 mb-4">
                           <label for="" class="col-form-label">Departure date</label>
                               <%= form.date_field :end_date, class: "form-control" %>
                         </div>
                       </div>

                       <div class="row">
                         <div class="col-md-12 form-group mt-4 mb-4">
                           <label for="" class="col-form-label">Reservation Notes (e.g. phone number, preferences)</label>
                               <%= form.text_field :message, class: "form-control" %>

                         </div>
                       </div>
                    
                       <div class="row">
                         <div class="col-md-12 form-group mb-4">
                           <input type="submit" class="btn btn-green rounded-0 py-2 px-4" name="commit" value="Create Reservation" data-disable-with="Create Reservation">
                           
                         </div>
                       </div>
                     </form>

                   </div>
                 </div>
               </div>
                    </div>

           </div>
           <div class="col-12 col-md-4 bg-one-bedroom-apartment" style="background-image: linear-gradient(0deg, rgba(29, 29, 29, 0.9), rgba(29, 29, 29, 0.9)), url('<%= rails_blob_url(@room.thumbnail_image) %>');"
>
             <div class="center">
             <p class="text-white font-libre-36"><%= @room.name%></p>
             <p class="text-white font-poppins-18"><%= @room.description%></p>
             <div class="row mx-auto justify-content-center">
             <div class="col-6">
               <button type="button" class="btn btn-light mt-5 py-3 px-3 rounded-0 font-poppins-button">Change Room</button>
             </div>
             </div>
             </div>
             </div>
         </div>
     </div>





	<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  

  <tbody>
    <% @reservations.where(restaurant_category_id: "7") do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.last_name %></td>
        <td><%= reservation.email %></td>
        <td><%= reservation.persons %></td>
        <td><%= reservation.start_date %></td>
        <td><%= reservation.end_date %></td>
        <td><%= reservation.message %></td>
        <td><%= link_to 'Show', room_reservations_path %></td>
        <td><%= link_to 'Edit', edit_room_reservation_path(@room , reservation) %></td>
        <td><%= link_to 'Destroy', [@room , reservation], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_room_reservation_path %>

app/views/reservations/new.html.erb
<%= render 'form', reservation: @reservation %>

<%
=begin%>
 <%= link_to 'Back', room_reservations_path %> 
<%
=end%>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @reservation.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reservation.email %>
</p>

<p>
  <strong>Persons:</strong>
  <%= @reservation.persons %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @reservation.start_date %>
</p>

<p>
  <strong>End time:</strong>
  <%= @reservation.end_date %>
</p>

<p>
  <strong>Message:</strong>
  <%= @reservation.message %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :thumbnail_image %>
    <%= form.file_field :thumbnail_image %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :images %>
  </div>

  <div class="field">
    <%= form.label :person %>
    <%= form.text_field :person %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= render "shared/navbar" %>

<section id="room" class="row intro-div no-gutters">

    <% @rooms.each do |room| %>
    <% if room.thumbnail_image.attached? %>>
      <div class="col-md-4 col-sm-12 col-xs-12 fill fill-res" style="background-image: linear-gradient(0deg, rgba(29, 29, 29, 0.7), rgba(29, 29, 29, 0.7)), url('<%= rails_blob_url(room.thumbnail_image) %>');">
      <% end %>
        <div class="room" >
        <h2 class="room-title"><%= room.name %>
</h2>
        <p class="room-text">     <%= room.description %>
</p>
</div>
      <div class="d-flex justify-content-center">

     <%= link_to room , class: "btn-get-room" do %>
        More Information
             <% end %>

      </div>
       

 <%= link_to 'Show', room %>
        <%= link_to 'Edit', edit_room_path(room) %>
       <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %>

      </div>
     

    <% end %>





<p id="notice"><%= notice %></p>


<%
=begin%>
 <%= link_to 'New Room', new_room_path %> 
<%
=end%>
  </section>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
</p>

<p>
  <strong>Description:</strong>
</p>

<p>
  <strong>Thumbnail image:</strong>
  <%= @room.thumbnail_image %>
</p>

<p>
  <strong>Images:</strong>
  <%= @room.images %>
</p>

<p>
  <strong>Person:</strong>
  <%= @room.person %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> | 
<%
=end%>


  <div class="container mt-4 py-5">
    <div class="row">
      <div class="col-4">
        <div class="p-3 bg-white">
          <div class="row">
            <span><i class="fa fa-arrow-left"></i><%= link_to 'Back', rooms_path , style: "color: #000; font-size:18px; text-decoration: none" %>
</span>
            <p class="text-black font-libre-48 mt-5 pt-3">  <%= @room.name %>
</p>
            <p class="text-black font-poppins-18a mt-3">  <%= @room.description %></p>
            <span class="mt-3"><i class="fa fa-arrows-alt"></i> Size: 30 m²</span>
            <span class="mt-4"><i class="fa fa-users"></i> Persons: 2</span>
            <span class="mt-4"><i class="fa fa-bed"></i> Beds: 1</span>
            <%= link_to 'Select room', new_room_reservation_path(@room), class: "btn btn-dark mt-5 py-3 px-3 rounded-0 font-poppins-button" , style: "color: #fff"%> 

          </div>
        </div>
      </div>
      <div class="col-4 px-1">
          <%= image_tag "soba1.png" , class: "pictures" %>
      </div>
      <div class="col-4 px-1">
          <%= image_tag "soba.png", class: "pictures" %>
      </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<body class="background-nav">

       <div id="wrapper">
         <!-- Sidebar -->
         <div id="sidebar-wrapper">
           <ul class="sidebar-nav">
             <div class="row margin-bottom">
               <div class="col-2 mb-2">
                 ENG
               </div>
               <div class="col-2 mb-2">
                 BH
               </div>
               <div class="col-2 mb-2">
                 RU
               </div>
               <hr>
               </div>
             <li><a href="#">Home</a></li>
             <li><a href="#">About Us</a></li>
             <li><a href="#">Reservation</a></li>
             <li><a href="#">Contact</a></li>
             <div class="row mt-5">
               <hr>
               <div class="col-6 mb-2">
                 Contact informations
               </div>
               <div class="col-6 mb-2">
                 BH
               </div>
               </div>
           </ul>
         </div>

         <!-- Page Content -->
         <div id="page-content-wrapper">
           <div class="container">
             <div class="row">
               <div class="col-lg-5">
                 <a href="#" class="btn mt-4" id="menu-toggle"><span><%= image_tag "menu.svg" %></span></a>
                 </div>
               <div class="col-lg-2">
                <%= link_to  root_path do  %>

                 <%= image_tag "logo.png" %>
                         <% end %>

               </div>
               <div class="col-lg-3">
               </div>
               <div class="col-lg-2">
                 <button type="button" class="btn btn-outline-light mt-3">Book Now</button>
               </div>
               <hr class="hr">
             </div>
           </div>
         </div>
       </div>

<script>
  $(document).ready(function(){
  $("#menu-toggle").click(function(e){
    e.preventDefault();
    $("#wrapper").toggleClass("menuDisplayed");
  });
});
</script>